# Generated by Django 4.1.4 on 2023-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customerinput_order_customer_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
