# Generated by Django 4.1.4 on 2023-02-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_order_tag_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='emali',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
